//
//  MovieDetailsPresenter.swift
//  MovieSample
//
//  Created by rajesh.rao on 07/10/2018.
//  Copyright (c) 2018 rajesh.rao. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailsPresentationLogic {
    func presentMovieDetails(response: MovieDetails.MetaData.Response)
    func presentError(error: Error)
}

class MovieDetailsPresenter: MovieDetailsPresentationLogic {
    weak var viewController: MovieDetailsDisplayLogic?
    
    // MARK: Do something
    
    func presentMovieDetails(response: MovieDetails.MetaData.Response) {
        let movieMetaData = response.movieMetaData
        let viewModel = MovieDetails.MetaData.ViewModel.Info.init(Actors: movieMetaData.Actors, Plot: movieMetaData.Plot, imdbRating: movieMetaData.imdbRating, Poster: movieMetaData.Poster)
        
        DispatchQueue.main.async { [weak self] in
            self?.viewController?.display(viewModel: MovieDetails.MetaData.ViewModel.init(info: viewModel))
        }
    }
    
    func presentError(error: Error) {
        DispatchQueue.main.async { [weak self] in
            self?.viewController?.displayError(error: error)
        }
    }
}
