//
//  MovieDetailsInteractor.swift
//  MovieSample
//
//  Created by rajesh.rao on 07/10/2018.
//  Copyright (c) 2018 rajesh.rao. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailsBusinessLogic {
  func getMovie(request: MovieDetails.Something.Request)
}

protocol MovieDetailsDataStore {
  var movie: Movie! { get set }
}

class MovieDetailsInteractor: MovieDetailsBusinessLogic, MovieDetailsDataStore {
  var presenter: MovieDetailsPresentationLogic?
  var worker: MovieDetailsWorker?
  var movie: Movie!
  
  // MARK: Do something
  
  func getMovie(request: MovieDetails.Something.Request)
  {
    worker = MovieDetailsWorker()
    worker?.doSomeWork()
    
    let response = MovieDetails.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
