//
//  MovieListRouter.swift
//  MovieSample
//
//  Created by rajesh.rao on 06/10/2018.
//  Copyright (c) 2018 rajesh.rao. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MovieListRoutingLogic {
    func routeToMovieDetails()
}

protocol MovieListDataPassing
{
    var dataStore: MovieListDataStore? { get }
}

class MovieListRouter: NSObject, MovieListRoutingLogic, MovieListDataPassing {
    weak var viewController: MovieListViewController?
    var dataStore: MovieListDataStore?
    
    // MARK: Routing
    
    func routeToMovieDetails()
    {
        let destinationVC = MovieDetailsViewController.init(nibName: nil, bundle: nil)
        var destinationDS = destinationVC.router!.dataStore!
        
        passData(from: dataStore!, destination: &destinationDS)
        viewController?.navigationController?.pushViewController(destinationVC, animated: true)
    }
    
    // MARK: Navigation
    
    func navigate(from source: MovieListViewController, destination: MovieDetailsViewController)
    {
       // source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passData(from source: MovieListDataStore , destination: inout MovieDetailsDataStore)
    {
        //let selectedRow = viewController!.tableView.indexPathForSelectedRow!.row
        //destination.movie = source.movies![selectedRow]
    }
}
