//
//  MovieListModels.swift
//  MovieSample
//
//  Created by rajesh.rao on 06/10/2018.
//  Copyright (c) 2018 rajesh.rao. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListMovies {
    enum FetchMovies {

        struct Response {
            var movies: [Movie]
        }
        
        struct ViewModel {
            struct Movie {
                var title: String
                var year: String
                var poster: String?
            }
            
            var movies: [ListMovies.FetchMovies.ViewModel.Movie]
        }
    }
}
